version: '3.1'

services:
  postgresdb:
    container_name: postgresdb
    image: postgres:13.5
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bank
    volumes:
      - bank-pgsql-data:/var/lib/postgresql/data
    networks:
      - docker_network

networks:
  docker_network:
    driver: bridge

volumes:
  bank-pgsql-data:
